/*              389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
 
Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.           */

import java.util.*;

//leetcode solution
class Solution 
{
    public char findTheDifference(String s, String t) 
    {    
        HashMap<Character,Integer>map=new HashMap<>();

        int sum=0;
        for( int i=0 ; i<s.length() ; i++ )
            sum=sum^(int)s.charAt(i);

        for( int i=0 ; i<t.length() ; i++ )
            sum=sum^(int)t.charAt(i);

        return (char)sum;
    }
}

//main class for drive the solution
public class Question389
{
    public static void main(String args[])
    {
        Scanner Sc=new Scanner(System.in);
        int tCase=Sc.nextInt();
        while( tCase-->0 )
        {
            String s=Sc.next();
            String t=Sc.next();
            Solution sl=new Solution();
            System.out.print( sl.findTheDifference( s, t) );
        } 
    }
}